# Generated by Django 3.2.2 on 2022-06-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_alter_profile_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
