# Generated by Django 3.2.2 on 2022-06-27 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_commerce', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_commerce.comic', verbose_name='Comic')),
                ('comic_qty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.wishlist', verbose_name='comic qty')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'e_commerce_purcharsed',
            },
        ),
    ]
