# Generated by Django 3.2.2 on 2022-06-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0013_purchaseorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
