# Generated by Django 3.2.2 on 2022-06-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0016_auto_20220627_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='qty_comic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='e_commerce.comic'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='title',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='e_commerce.wishlist'),
        ),
    ]
