# Generated by Django 3.2.2 on 2022-06-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0017_auto_20220627_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='buied_qty',
            field=models.PositiveIntegerField(default=1, verbose_name='buied qty'),
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
