# Generated by Django 3.2.2 on 2022-06-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0019_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wished_qty',
            field=models.PositiveIntegerField(default=1, verbose_name='wished qty'),
        ),
    ]
