# Generated by Django 3.2.2 on 2022-06-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0022_purchaseorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
