# Generated by Django 3.2.2 on 2022-06-27 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('e_commerce', '0023_delete_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('title', models.CharField(max_length=30)),
                ('qty_comic', models.IntegerField()),
            ],
            options={
                'db_table': 'e_commerce_purchase_order',
            },
        ),
    ]
